camunda:
  bpm:
    history-level: Full
    id-generator: strong
    filter:
        create: All tasks
    admin-user:
      id: admin
      password: rules
      firstName: Admin
      lastName: istrator
      email: mikeryan56@gmail.com


spring:
  application:
    name: abc

#    server.servlet.context-path