camunda:
  bpm:
    history-level: Full
    id-generator: strong
    auto-deployment-enabled: true
    filter:
        create: All tasks
    admin-user:
      id: admin
      password: rules
      firstName: Admin
      lastName: istrator
      email: mrstu@live.com


spring:
  application:
    name: abc

#    server.servlet.context-path